### ISSUE TITLE
support older javascript engines

### ISSUE THREAD

**Issue by stephenmathieson** [componentjs/require2#5]
[this](https://github.com/componentjs/require2/blob/master/index.js#L35-L37) wont work without es5 :/

**Comment by timaschew** [comment]
you mean indexOf and filter?
you know a good polyfill?

**Comment by stephenmathieson** [comment]
looks like you rewrote all that stuff, so it doesnt matter anymore

**Comment by timaschew** [comment]
yes, I realized, that it's not so easy to sort semantic versions ^^
